//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string text { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<int> FK_Id_Modulo { get; set; }
        public Nullable<int> FK_Id_Profesor { get; set; }
        public string Modulo { get; set; }
        public string Profesor { get; set; }
    
        public virtual Modulo Modulo1 { get; set; }
        public virtual Profesor Profesor1 { get; set; }
    }
}
