//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaScheduler.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materia()
        {
            this.Modulo = new HashSet<Modulo>();
            this.Pensum_Materia = new HashSet<Pensum_Materia>();
        }
    
        public int Id_Materia { get; set; }
        [DisplayName("Nombre de Materia")]
        public string Nombre { get; set; }
        [DisplayName("NRC")]
        public string Codigo { get; set; }
        public int FK_Id_Programa { get; set; }
    
        public virtual Programa Programa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modulo> Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pensum_Materia> Pensum_Materia { get; set; }
    }
}
