//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pensum_Materia
    {
        public int FK_Id_Pensum { get; set; }
        public int FK_id_Materia { get; set; }
        public int Creditos { get; set; }
        public int semestre { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Pensum Pensum { get; set; }
    }
}
