//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFacultad
    {
        public int Id_Facultad { get; set; }
        public string Nombre { get; set; }
        public int FK_Id_Sede { get; set; }
        public string nombreSede { get; set; }
    }
}
